version: '3.5'
services:
  dipol-dominio-service:
    image: registry.local.com.br/dipol-endereco-service:1.0.0
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms128m -Xmx128m
      - KEYCLOAK_SERVER_URL=http://10.75.200.38:8081/auth
      - KEYCLOAK_REALM=dipol
      - KEYCLOAK_CLIENT_ID=dipol-microservices
      - "KEYCLOAK_CLIENT_SECRET=b1de7cc3-a17a-4994-b987-a7da9264b95e"
      - EUREKA_CLIENT_ENABLED=true      
      - DATASOURCE_URL=jdbc:postgresql://localhost:5432/gisdb
      - DATASOURCE_USERNAME=postgis
      - "DATASOURCE_PASSWORD=root"
      - "GOOGLE_API_KEY=AIzaSyAexZ4KZot11RpJfyR-LeKoKZhuzMOfpSc"
    ports:
      - 3013:3013
    networks:
      - microservices
    volumes:
      - /opt/log:/opt/log
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 200M
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
        window: 120s
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.5

networks:
  microservices:
    driver: overlay
